# Generated by Django 3.1.7 on 2021-03-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUserPreferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuserpreferences',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
